CREATE TABLE IF NOT EXISTS analytics (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    website_url VARCHAR(254) NOT NULL,
    ping5 INTEGER,
    checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (website_url) REFERENCES ownership(website_url) ON DELETE CASCADE
);
